"""
Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

from helpers import fibonacci

LIMIT = 4_000_000
F1, F2 = 1, 1


def solution():
    result = 0

    fibo = fibonacci(F1, F2)
    while (number := next(fibo)) < LIMIT:
        if number % 2 == 0:
            result += number

    return result


if __name__ == "__main__":
    print(solution())
