"""
Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""


def fibonacci_generator(F1, F2):
    a = F1
    yield a
    b = F2
    yield b
    while True:
        a, b = b, a + b
        yield b


def solution(bound, F1, F2):
    fibonacci = fibonacci_generator(F1, F2)
    result = 0
    while (number := next(fibonacci)) < bound:
        if number % 2 == 0:
            result += number
    return result


if __name__ == "__main__":
    bound = 4000000
    F1, F2 = 1, 1

    print(solution(bound, F1, F2))
