"""
Problem 45: Triangular, pentagonal, and hexagonal

Triangular, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle   Tn=n(n+1)/2  1, 3, 6, 10, 15, ...
Pentagonal Pn=n(3n−1)/2  1, 5, 12, 22, 35, ...
Hexagonal  Hn=n(2n−1)  1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangular number that is also pentagonal and hexagonal.
"""

from itertools import count


def generator():
    T = (int(n * (n + 1) / 2) for n in count())
    P = (int(n * (3 * n - 1) / 2) for n in count())
    H = (int(n * (2 * n - 1)) for n in count())

    t = next(T)
    p = next(P)
    h = next(H)

    while True:

        max_ = max(t, p, h)
        if t < max_:
            t = next(T)
        if p < max_:
            p = next(P)
        if h < max_:
            h = next(H)

        if t == p == h:
            yield t
            t = next(T)
            p = next(P)
            h = next(H)


def solution(bound):
    gene = generator()
    while (number := next(gene)) <= bound:
        continue
    return number


if __name__ == "__main__":
    bound = 40755

    print(solution(bound))
